"""add_notifications_activities

Revision ID: 2db67c628ccb
Revises: 6cf16f3706b5
Create Date: 2026-07-07 10:11:03.205791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db67c628ccb'
down_revision: Union[str, None] = '6cf16f3706b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_activity_logs_action'), 'fastapi_activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_fastapi_activity_logs_entity_id'), 'fastapi_activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fastapi_activity_logs_entity_type'), 'fastapi_activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_fastapi_activity_logs_user_id'), 'fastapi_activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_fastapi_activity_logs_workspace_id'), 'fastapi_activity_logs', ['workspace_id'], unique=False)
    op.create_table('fastapi_notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_notifications_user_id'), 'fastapi_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_fastapi_notifications_workspace_id'), 'fastapi_notifications', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_notifications_workspace_id'), table_name='fastapi_notifications')
    op.drop_index(op.f('ix_fastapi_notifications_user_id'), table_name='fastapi_notifications')
    op.drop_table('fastapi_notifications')
    op.drop_index(op.f('ix_fastapi_activity_logs_workspace_id'), table_name='fastapi_activity_logs')
    op.drop_index(op.f('ix_fastapi_activity_logs_user_id'), table_name='fastapi_activity_logs')
    op.drop_index(op.f('ix_fastapi_activity_logs_entity_type'), table_name='fastapi_activity_logs')
    op.drop_index(op.f('ix_fastapi_activity_logs_entity_id'), table_name='fastapi_activity_logs')
    op.drop_index(op.f('ix_fastapi_activity_logs_action'), table_name='fastapi_activity_logs')
    op.drop_table('fastapi_activity_logs')
    # ### end Alembic commands ###
