"""add_client_case_draft

Revision ID: 400b9ef03d63
Revises: be95ef2a1f07
Create Date: 2026-07-05 16:44:47.803649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400b9ef03d63'
down_revision: Union[str, None] = 'be95ef2a1f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_clients',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_clients_email'), 'fastapi_clients', ['email'], unique=False)
    op.create_index(op.f('ix_fastapi_clients_full_name'), 'fastapi_clients', ['full_name'], unique=False)
    op.create_index(op.f('ix_fastapi_clients_workspace_id'), 'fastapi_clients', ['workspace_id'], unique=False)
    op.create_table('fastapi_cases',
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('case_type', sa.String(length=100), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=False),
    sa.Column('judge', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hearing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['fastapi_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_cases_case_number'), 'fastapi_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_fastapi_cases_case_type'), 'fastapi_cases', ['case_type'], unique=False)
    op.create_index(op.f('ix_fastapi_cases_client_id'), 'fastapi_cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_fastapi_cases_court'), 'fastapi_cases', ['court'], unique=False)
    op.create_index(op.f('ix_fastapi_cases_status'), 'fastapi_cases', ['status'], unique=False)
    op.create_index(op.f('ix_fastapi_cases_title'), 'fastapi_cases', ['title'], unique=False)
    op.create_index(op.f('ix_fastapi_cases_workspace_id'), 'fastapi_cases', ['workspace_id'], unique=False)
    op.create_table('fastapi_drafts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['fastapi_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['fastapi_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_drafts_case_id'), 'fastapi_drafts', ['case_id'], unique=False)
    op.create_index(op.f('ix_fastapi_drafts_created_by'), 'fastapi_drafts', ['created_by'], unique=False)
    op.create_index(op.f('ix_fastapi_drafts_title'), 'fastapi_drafts', ['title'], unique=False)
    op.create_index(op.f('ix_fastapi_drafts_workspace_id'), 'fastapi_drafts', ['workspace_id'], unique=False)
    op.add_column('fastapi_files', sa.Column('case_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_fastapi_files_case_id'), 'fastapi_files', ['case_id'], unique=False)
    op.create_foreign_key(None, 'fastapi_files', 'fastapi_cases', ['case_id'], ['id'], ondelete='SET NULL')
    op.add_column('fastapi_workspaces', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('fastapi_workspaces', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_fastapi_workspaces_owner_id'), 'fastapi_workspaces', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'fastapi_workspaces', 'fastapi_users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fastapi_workspaces', type_='foreignkey')
    op.drop_index(op.f('ix_fastapi_workspaces_owner_id'), table_name='fastapi_workspaces')
    op.drop_column('fastapi_workspaces', 'owner_id')
    op.drop_column('fastapi_workspaces', 'description')
    op.drop_constraint(None, 'fastapi_files', type_='foreignkey')
    op.drop_index(op.f('ix_fastapi_files_case_id'), table_name='fastapi_files')
    op.drop_column('fastapi_files', 'case_id')
    op.drop_index(op.f('ix_fastapi_drafts_workspace_id'), table_name='fastapi_drafts')
    op.drop_index(op.f('ix_fastapi_drafts_title'), table_name='fastapi_drafts')
    op.drop_index(op.f('ix_fastapi_drafts_created_by'), table_name='fastapi_drafts')
    op.drop_index(op.f('ix_fastapi_drafts_case_id'), table_name='fastapi_drafts')
    op.drop_table('fastapi_drafts')
    op.drop_index(op.f('ix_fastapi_cases_workspace_id'), table_name='fastapi_cases')
    op.drop_index(op.f('ix_fastapi_cases_title'), table_name='fastapi_cases')
    op.drop_index(op.f('ix_fastapi_cases_status'), table_name='fastapi_cases')
    op.drop_index(op.f('ix_fastapi_cases_court'), table_name='fastapi_cases')
    op.drop_index(op.f('ix_fastapi_cases_client_id'), table_name='fastapi_cases')
    op.drop_index(op.f('ix_fastapi_cases_case_type'), table_name='fastapi_cases')
    op.drop_index(op.f('ix_fastapi_cases_case_number'), table_name='fastapi_cases')
    op.drop_table('fastapi_cases')
    op.drop_index(op.f('ix_fastapi_clients_workspace_id'), table_name='fastapi_clients')
    op.drop_index(op.f('ix_fastapi_clients_full_name'), table_name='fastapi_clients')
    op.drop_index(op.f('ix_fastapi_clients_email'), table_name='fastapi_clients')
    op.drop_table('fastapi_clients')
    # ### end Alembic commands ###
