"""add_template_versions

Revision ID: 450ecc6c9d4c
Revises: e51fcfe80b76
Create Date: 2026-07-07 10:50:28.663527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450ecc6c9d4c'
down_revision: Union[str, None] = 'e51fcfe80b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_versions',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('preview_text', sa.Text(), nullable=True),
    sa.Column('placeholders', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_versions_created_by'), 'template_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_template_versions_file_id'), 'template_versions', ['file_id'], unique=False)
    op.create_index(op.f('ix_template_versions_template_id'), 'template_versions', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_versions_template_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_file_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_created_by'), table_name='template_versions')
    op.drop_table('template_versions')
    # ### end Alembic commands ###
