"""add_company_to_client_priority_to_case

Revision ID: 6cf16f3706b5
Revises: 9e7bf4fbffe8
Create Date: 2026-07-07 09:37:15.971216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf16f3706b5'
down_revision: Union[str, None] = '9e7bf4fbffe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastapi_cases', sa.Column('priority', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_fastapi_cases_priority'), 'fastapi_cases', ['priority'], unique=False)
    op.add_column('fastapi_clients', sa.Column('company', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fastapi_clients', 'company')
    op.drop_index(op.f('ix_fastapi_cases_priority'), table_name='fastapi_cases')
    op.drop_column('fastapi_cases', 'priority')
    # ### end Alembic commands ###
