"""add_case_timeline_field

Revision ID: 9e7bf4fbffe8
Revises: 400b9ef03d63
Create Date: 2026-07-05 16:45:32.142499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7bf4fbffe8'
down_revision: Union[str, None] = '400b9ef03d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastapi_cases', sa.Column('timeline', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fastapi_cases', 'timeline')
    # ### end Alembic commands ###
