"""Add auth, workspace, storage, and ai tables with invitations

Revision ID: be95ef2a1f07
Revises: 
Create Date: 2026-07-05 15:46:46.628679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'be95ef2a1f07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_organizations_name'), 'fastapi_organizations', ['name'], unique=False)
    op.create_index(op.f('ix_fastapi_organizations_slug'), 'fastapi_organizations', ['slug'], unique=True)
    op.create_table('fastapi_permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_permissions_name'), 'fastapi_permissions', ['name'], unique=True)
    op.create_table('fastapi_roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_roles_name'), 'fastapi_roles', ['name'], unique=True)
    op.create_table('fastapi_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_users_email'), 'fastapi_users', ['email'], unique=True)
    op.create_table('fastapi_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['fastapi_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['fastapi_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('fastapi_user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['fastapi_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fastapi_user_role_unique', 'fastapi_user_roles', ['user_id', 'role_id'], unique=True)
    op.create_index(op.f('ix_fastapi_user_roles_role_id'), 'fastapi_user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_fastapi_user_roles_user_id'), 'fastapi_user_roles', ['user_id'], unique=False)
    op.create_table('fastapi_workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['fastapi_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_fastapi_workspace_org_slug')
    )
    op.create_index(op.f('ix_fastapi_workspaces_name'), 'fastapi_workspaces', ['name'], unique=False)
    op.create_index(op.f('ix_fastapi_workspaces_organization_id'), 'fastapi_workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fastapi_workspaces_slug'), 'fastapi_workspaces', ['slug'], unique=False)
    op.create_table('fastapi_ai_conversations',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_ai_conversations_user_id'), 'fastapi_ai_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_fastapi_ai_conversations_workspace_id'), 'fastapi_ai_conversations', ['workspace_id'], unique=False)
    op.create_table('fastapi_ai_memories',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_ai_memories_key'), 'fastapi_ai_memories', ['key'], unique=False)
    op.create_index(op.f('ix_fastapi_ai_memories_user_id'), 'fastapi_ai_memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_fastapi_ai_memories_workspace_id'), 'fastapi_ai_memories', ['workspace_id'], unique=False)
    op.create_table('fastapi_folders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['fastapi_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'parent_id', 'name', name='uq_fastapi_folder_workspace_parent_name')
    )
    op.create_index(op.f('ix_fastapi_folders_name'), 'fastapi_folders', ['name'], unique=False)
    op.create_index(op.f('ix_fastapi_folders_parent_id'), 'fastapi_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_fastapi_folders_workspace_id'), 'fastapi_folders', ['workspace_id'], unique=False)
    op.create_table('fastapi_workspace_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['fastapi_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_workspace_invitations_email'), 'fastapi_workspace_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_fastapi_workspace_invitations_invited_by'), 'fastapi_workspace_invitations', ['invited_by'], unique=False)
    op.create_index(op.f('ix_fastapi_workspace_invitations_token'), 'fastapi_workspace_invitations', ['token'], unique=True)
    op.create_index(op.f('ix_fastapi_workspace_invitations_workspace_id'), 'fastapi_workspace_invitations', ['workspace_id'], unique=False)
    op.create_table('fastapi_workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_fastapi_workspace_member_user')
    )
    op.create_index(op.f('ix_fastapi_workspace_members_user_id'), 'fastapi_workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_fastapi_workspace_members_workspace_id'), 'fastapi_workspace_members', ['workspace_id'], unique=False)
    op.create_table('fastapi_ai_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_streaming_finished', sa.Boolean(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['fastapi_ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_ai_messages_conversation_id'), 'fastapi_ai_messages', ['conversation_id'], unique=False)
    op.create_table('fastapi_files',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['fastapi_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['fastapi_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_files_created_by'), 'fastapi_files', ['created_by'], unique=False)
    op.create_index(op.f('ix_fastapi_files_folder_id'), 'fastapi_files', ['folder_id'], unique=False)
    op.create_index(op.f('ix_fastapi_files_mime_type'), 'fastapi_files', ['mime_type'], unique=False)
    op.create_index(op.f('ix_fastapi_files_name'), 'fastapi_files', ['name'], unique=False)
    op.create_index(op.f('ix_fastapi_files_workspace_id'), 'fastapi_files', ['workspace_id'], unique=False)
    op.create_table('fastapi_file_versions',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['fastapi_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['fastapi_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'version_number', name='uq_fastapi_file_version_number')
    )
    op.create_index(op.f('ix_fastapi_file_versions_created_by'), 'fastapi_file_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_fastapi_file_versions_file_id'), 'fastapi_file_versions', ['file_id'], unique=False)
    op.create_table('fastapi_embeddings',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('chunk_content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('source_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['fastapi_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_version_id'], ['fastapi_file_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['fastapi_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_embeddings_source_file_id'), 'fastapi_embeddings', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_fastapi_embeddings_source_version_id'), 'fastapi_embeddings', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_fastapi_embeddings_workspace_id'), 'fastapi_embeddings', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_embeddings_workspace_id'), table_name='fastapi_embeddings')
    op.drop_index(op.f('ix_fastapi_embeddings_source_version_id'), table_name='fastapi_embeddings')
    op.drop_index(op.f('ix_fastapi_embeddings_source_file_id'), table_name='fastapi_embeddings')
    op.drop_table('fastapi_embeddings')
    op.drop_index(op.f('ix_fastapi_file_versions_file_id'), table_name='fastapi_file_versions')
    op.drop_index(op.f('ix_fastapi_file_versions_created_by'), table_name='fastapi_file_versions')
    op.drop_table('fastapi_file_versions')
    op.drop_index(op.f('ix_fastapi_files_workspace_id'), table_name='fastapi_files')
    op.drop_index(op.f('ix_fastapi_files_name'), table_name='fastapi_files')
    op.drop_index(op.f('ix_fastapi_files_mime_type'), table_name='fastapi_files')
    op.drop_index(op.f('ix_fastapi_files_folder_id'), table_name='fastapi_files')
    op.drop_index(op.f('ix_fastapi_files_created_by'), table_name='fastapi_files')
    op.drop_table('fastapi_files')
    op.drop_index(op.f('ix_fastapi_ai_messages_conversation_id'), table_name='fastapi_ai_messages')
    op.drop_table('fastapi_ai_messages')
    op.drop_index(op.f('ix_fastapi_workspace_members_workspace_id'), table_name='fastapi_workspace_members')
    op.drop_index(op.f('ix_fastapi_workspace_members_user_id'), table_name='fastapi_workspace_members')
    op.drop_table('fastapi_workspace_members')
    op.drop_index(op.f('ix_fastapi_workspace_invitations_workspace_id'), table_name='fastapi_workspace_invitations')
    op.drop_index(op.f('ix_fastapi_workspace_invitations_token'), table_name='fastapi_workspace_invitations')
    op.drop_index(op.f('ix_fastapi_workspace_invitations_invited_by'), table_name='fastapi_workspace_invitations')
    op.drop_index(op.f('ix_fastapi_workspace_invitations_email'), table_name='fastapi_workspace_invitations')
    op.drop_table('fastapi_workspace_invitations')
    op.drop_index(op.f('ix_fastapi_folders_workspace_id'), table_name='fastapi_folders')
    op.drop_index(op.f('ix_fastapi_folders_parent_id'), table_name='fastapi_folders')
    op.drop_index(op.f('ix_fastapi_folders_name'), table_name='fastapi_folders')
    op.drop_table('fastapi_folders')
    op.drop_index(op.f('ix_fastapi_ai_memories_workspace_id'), table_name='fastapi_ai_memories')
    op.drop_index(op.f('ix_fastapi_ai_memories_user_id'), table_name='fastapi_ai_memories')
    op.drop_index(op.f('ix_fastapi_ai_memories_key'), table_name='fastapi_ai_memories')
    op.drop_table('fastapi_ai_memories')
    op.drop_index(op.f('ix_fastapi_ai_conversations_workspace_id'), table_name='fastapi_ai_conversations')
    op.drop_index(op.f('ix_fastapi_ai_conversations_user_id'), table_name='fastapi_ai_conversations')
    op.drop_table('fastapi_ai_conversations')
    op.drop_index(op.f('ix_fastapi_workspaces_slug'), table_name='fastapi_workspaces')
    op.drop_index(op.f('ix_fastapi_workspaces_organization_id'), table_name='fastapi_workspaces')
    op.drop_index(op.f('ix_fastapi_workspaces_name'), table_name='fastapi_workspaces')
    op.drop_table('fastapi_workspaces')
    op.drop_index(op.f('ix_fastapi_user_roles_user_id'), table_name='fastapi_user_roles')
    op.drop_index(op.f('ix_fastapi_user_roles_role_id'), table_name='fastapi_user_roles')
    op.drop_index('idx_fastapi_user_role_unique', table_name='fastapi_user_roles')
    op.drop_table('fastapi_user_roles')
    op.drop_table('fastapi_role_permissions')
    op.drop_index(op.f('ix_fastapi_users_email'), table_name='fastapi_users')
    op.drop_table('fastapi_users')
    op.drop_index(op.f('ix_fastapi_roles_name'), table_name='fastapi_roles')
    op.drop_table('fastapi_roles')
    op.drop_index(op.f('ix_fastapi_permissions_name'), table_name='fastapi_permissions')
    op.drop_table('fastapi_permissions')
    op.drop_index(op.f('ix_fastapi_organizations_slug'), table_name='fastapi_organizations')
    op.drop_index(op.f('ix_fastapi_organizations_name'), table_name='fastapi_organizations')
    op.drop_table('fastapi_organizations')
    # ### end Alembic commands ###
