"""add_workflow_engine_models

Revision ID: d120362c49ba
Revises: 2db67c628ccb
Create Date: 2026-07-07 10:30:06.692204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd120362c49ba'
down_revision: Union[str, None] = '2db67c628ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_case_notes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['fastapi_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['fastapi_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_case_notes_case_id'), 'fastapi_case_notes', ['case_id'], unique=False)
    op.create_index(op.f('ix_fastapi_case_notes_created_by'), 'fastapi_case_notes', ['created_by'], unique=False)
    op.create_table('fastapi_hearings',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('hearing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hearing_time', sa.String(length=50), nullable=True),
    sa.Column('court_name', sa.String(length=255), nullable=True),
    sa.Column('court_hall', sa.String(length=50), nullable=True),
    sa.Column('judge_name', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=500), nullable=True),
    sa.Column('next_hearing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['fastapi_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_hearings_case_id'), 'fastapi_hearings', ['case_id'], unique=False)
    op.create_table('fastapi_tasks',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['fastapi_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['fastapi_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_tasks_assigned_to'), 'fastapi_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_fastapi_tasks_case_id'), 'fastapi_tasks', ['case_id'], unique=False)
    op.create_table('fastapi_timeline_events',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['fastapi_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_timeline_events_case_id'), 'fastapi_timeline_events', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_timeline_events_case_id'), table_name='fastapi_timeline_events')
    op.drop_table('fastapi_timeline_events')
    op.drop_index(op.f('ix_fastapi_tasks_case_id'), table_name='fastapi_tasks')
    op.drop_index(op.f('ix_fastapi_tasks_assigned_to'), table_name='fastapi_tasks')
    op.drop_table('fastapi_tasks')
    op.drop_index(op.f('ix_fastapi_hearings_case_id'), table_name='fastapi_hearings')
    op.drop_table('fastapi_hearings')
    op.drop_index(op.f('ix_fastapi_case_notes_created_by'), table_name='fastapi_case_notes')
    op.drop_index(op.f('ix_fastapi_case_notes_case_id'), table_name='fastapi_case_notes')
    op.drop_table('fastapi_case_notes')
    # ### end Alembic commands ###
