"""add_file_intelligence

Revision ID: e51fcfe80b76
Revises: d120362c49ba
Create Date: 2026-07-07 10:44:45.005260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51fcfe80b76'
down_revision: Union[str, None] = 'd120362c49ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_intelligence',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('case_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.String(length=100), nullable=True),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('document_title', sa.String(length=255), nullable=True),
    sa.Column('parties', sa.Text(), nullable=True),
    sa.Column('important_dates', sa.Text(), nullable=True),
    sa.Column('clause_headings', sa.Text(), nullable=True),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_intelligence_file_id'), 'file_intelligence', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_intelligence_file_id'), table_name='file_intelligence')
    op.drop_table('file_intelligence')
    # ### end Alembic commands ###
