import type {
  User,
  Draft,
  Template,
  Case,
  Clause,
  AuditLog,
  Notification,
  AnalyticsData,
  DraftTrend,
} from "@/types";

export const mockCurrentUser: User = {
  id: "u1",
  name: "Rajesh Sharma",
  email: "rajesh.sharma@lexfirm.in",
  role: "admin",
  isActive: true,
  firm: "Lex & Associates",
  createdAt: "2023-01-15T00:00:00Z",
  lastActive: new Date().toISOString(),
};

export const mockUsers: User[] = [
  mockCurrentUser,
  {
    id: "u2",
    name: "Priya Mehta",
    email: "priya.mehta@lexfirm.in",
    role: "lawyer",
    isActive: true,
    firm: "Lex & Associates",
    createdAt: "2023-03-10T00:00:00Z",
    lastActive: "2024-06-07T14:23:00Z",
  },
  {
    id: "u3",
    name: "Arjun Kapoor",
    email: "arjun.kapoor@lexfirm.in",
    role: "lawyer",
    isActive: true,
    firm: "Lex & Associates",
    createdAt: "2023-06-01T00:00:00Z",
    lastActive: "2024-06-07T11:00:00Z",
  },
  {
    id: "u4",
    name: "Sneha Patel",
    email: "sneha.patel@lexfirm.in",
    role: "legal-assistant",
    isActive: false,
    firm: "Lex & Associates",
    createdAt: "2023-08-20T00:00:00Z",
    lastActive: "2024-05-15T09:30:00Z",
  },
  {
    id: "u5",
    name: "Vikram Nair",
    email: "vikram.nair@lexfirm.in",
    role: "legal-assistant",
    isActive: true,
    firm: "Lex & Associates",
    createdAt: "2024-01-05T00:00:00Z",
    lastActive: "2024-06-08T08:00:00Z",
  },
];

export const mockDrafts: Draft[] = [
  {
    id: "d1",
    title: "Bail Application — State vs. Rajan Kumar",
    caseNumber: "CAS-2024-1042",
    clientName: "Rajan Kumar",
    status: "finalized",
    category: "criminal",
    assignedTo: "Priya Mehta",
    createdAt: "2024-05-28T10:00:00Z",
    updatedAt: "2024-06-05T14:30:00Z",
    wordCount: 2847,
    version: 3,
    tags: ["bail", "session court", "criminal"],
  },
  {
    id: "d2",
    title: "Property Dispute — Sharma Family vs. Builder Corp",
    caseNumber: "CAS-2024-0987",
    clientName: "Sharma Family",
    status: "in-progress",
    category: "property",
    assignedTo: "Rajesh Sharma",
    createdAt: "2024-06-01T09:00:00Z",
    updatedAt: "2024-06-07T16:00:00Z",
    wordCount: 5234,
    version: 2,
    tags: ["property", "civil court", "builder dispute"],
  },
  {
    id: "d3",
    title: "Divorce Petition — Meena vs. Suresh",
    caseNumber: "CAS-2024-1103",
    clientName: "Meena Verma",
    status: "review",
    category: "family",
    assignedTo: "Arjun Kapoor",
    createdAt: "2024-06-03T11:00:00Z",
    updatedAt: "2024-06-07T10:00:00Z",
    wordCount: 3102,
    version: 1,
    tags: ["divorce", "family court", "contested"],
  },
  {
    id: "d4",
    title: "Injunction Application — Tech Innovations Ltd.",
    caseNumber: "CAS-2024-0834",
    clientName: "Tech Innovations Ltd.",
    status: "draft",
    category: "civil",
    assignedTo: "Priya Mehta",
    createdAt: "2024-06-07T08:00:00Z",
    updatedAt: "2024-06-07T08:00:00Z",
    wordCount: 890,
    version: 1,
    tags: ["injunction", "civil", "commercial"],
  },
  {
    id: "d5",
    title: "Consumer Complaint — Anil Gupta vs. Insurance Co.",
    caseNumber: "CAS-2024-0923",
    clientName: "Anil Gupta",
    status: "finalized",
    category: "civil",
    assignedTo: "Rajesh Sharma",
    createdAt: "2024-05-20T09:00:00Z",
    updatedAt: "2024-05-30T15:00:00Z",
    wordCount: 1876,
    version: 4,
    tags: ["consumer", "insurance", "NCDRC"],
  },
  {
    id: "d6",
    title: "Lease Agreement — Commercial Property",
    caseNumber: "CAS-2024-1201",
    clientName: "Rohan Enterprises",
    status: "in-progress",
    category: "property",
    assignedTo: "Arjun Kapoor",
    createdAt: "2024-06-05T12:00:00Z",
    updatedAt: "2024-06-08T09:00:00Z",
    wordCount: 4102,
    version: 2,
    tags: ["lease", "commercial", "real estate"],
  },
  {
    id: "d7",
    title: "FIR Quashing Petition — High Court",
    caseNumber: "CAS-2024-1089",
    clientName: "Dev Malhotra",
    status: "archived",
    category: "criminal",
    assignedTo: "Priya Mehta",
    createdAt: "2024-04-10T09:00:00Z",
    updatedAt: "2024-05-01T11:00:00Z",
    wordCount: 3450,
    version: 5,
    tags: ["FIR", "quashing", "High Court"],
  },
  {
    id: "d8",
    title: "Child Custody Agreement — Joint Custody",
    caseNumber: "CAS-2024-1156",
    clientName: "Kavita Singh",
    status: "draft",
    category: "family",
    assignedTo: "Vikram Nair",
    createdAt: "2024-06-08T07:30:00Z",
    updatedAt: "2024-06-08T07:30:00Z",
    wordCount: 0,
    version: 1,
    tags: ["custody", "family court", "settlement"],
  },
];

export const mockTemplates: Template[] = [
  {
    id: "t1",
    name: "Bail Application",
    description:
      "Standard bail application for sessions court under CrPC Section 439",
    category: "criminal",
    fields: 12,
    usageCount: 847,
    lastUsed: "2024-06-07T14:00:00Z",
    previewText:
      "IN THE COURT OF SESSIONS JUDGE...\n\nIN THE MATTER OF:\n[Accused Name], S/o [Father Name]...\nAPPLICATION FOR BAIL UNDER SECTION 439...",
    tags: ["bail", "sessions court", "CrPC 439"],
    isFeatured: true,
  },
  {
    id: "t2",
    name: "FIR Quashing Petition",
    description:
      "Petition to quash FIR under Section 482 CrPC before High Court",
    category: "criminal",
    fields: 15,
    usageCount: 423,
    lastUsed: "2024-06-06T10:00:00Z",
    previewText:
      "IN THE HIGH COURT OF JUDICATURE...\n\nCRIMINAL MISC. PETITION NO. ___/2024\n\nIN THE MATTER OF:\nA petition under Section 482 CrPC...",
    tags: ["FIR", "quashing", "482 CrPC", "High Court"],
    isFeatured: false,
  },
  {
    id: "t3",
    name: "Civil Suit Plaint",
    description:
      "Standard plaint for civil suits including money recovery and injunctions",
    category: "civil",
    fields: 18,
    usageCount: 612,
    lastUsed: "2024-06-07T09:00:00Z",
    previewText:
      "IN THE COURT OF CIVIL JUDGE...\n\nCIVIL SUIT NO. ___/2024\n\nBETWEEN:\n[Plaintiff Name]... PLAINTIFF\nVS\n[Defendant Name]... DEFENDANT",
    tags: ["civil suit", "plaint", "CPC"],
    isFeatured: true,
  },
  {
    id: "t4",
    name: "Property Sale Agreement",
    description:
      "Comprehensive sale deed for residential and commercial property transactions",
    category: "property",
    fields: 22,
    usageCount: 389,
    lastUsed: "2024-06-05T15:00:00Z",
    previewText:
      "THIS AGREEMENT OF SALE is made and entered into on this ___ day of ___...\n\nBETWEEN:\n[Seller Name], hereinafter referred to as the SELLER...",
    tags: ["sale deed", "property", "real estate"],
    isFeatured: true,
  },
  {
    id: "t5",
    name: "Divorce Petition (Mutual)",
    description:
      "Mutual consent divorce petition under Section 13B Hindu Marriage Act",
    category: "family",
    fields: 16,
    usageCount: 267,
    lastUsed: "2024-06-04T11:00:00Z",
    previewText:
      "IN THE COURT OF FAMILY JUDGE...\n\nPETITION FOR DIVORCE BY MUTUAL CONSENT\nUNDER SECTION 13B OF THE HINDU MARRIAGE ACT, 1955",
    tags: ["divorce", "mutual consent", "HMA 13B"],
    isFeatured: false,
  },
  {
    id: "t6",
    name: "Lease Agreement",
    description: "Commercial and residential lease agreement template",
    category: "property",
    fields: 20,
    usageCount: 534,
    lastUsed: "2024-06-08T08:00:00Z",
    previewText:
      "THIS LEASE AGREEMENT is made on this ___ day of ___...\n\nBETWEEN:\n[Landlord Name], hereinafter referred to as the LESSOR...",
    tags: ["lease", "rent", "commercial"],
    isFeatured: true,
  },
  {
    id: "t7",
    name: "Consumer Complaint",
    description:
      "Consumer complaint before District Consumer Forum under Consumer Protection Act 2019",
    category: "civil",
    fields: 14,
    usageCount: 198,
    lastUsed: "2024-06-06T13:00:00Z",
    previewText:
      "BEFORE THE DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION...\n\nCOMPLAINT CASE NO. ___/2024\n\nIN THE MATTER OF:\n[Consumer Name], Son/Daughter of...",
    tags: ["consumer", "NCDRC", "Consumer Protection Act"],
    isFeatured: false,
  },
  {
    id: "t8",
    name: "Child Custody Petition",
    description:
      "Petition for child custody under Guardians and Wards Act 1890",
    category: "family",
    fields: 13,
    usageCount: 156,
    lastUsed: "2024-06-03T10:00:00Z",
    previewText:
      "IN THE COURT OF DISTRICT JUDGE (FAMILY COURT)...\n\nGUARDIANSHIP PETITION NO. ___/2024\n\nIN THE MATTER OF:\nPetition for Custody of Minor Child...",
    tags: ["custody", "guardianship", "family court"],
    isFeatured: false,
  },
];

export const mockCases: Case[] = [
  {
    id: "c1",
    caseNumber: "CAS-2024-1042",
    title: "IPC 420 Allegations",
    clientName: "Rajan Kumar",
    clientEmail: "rajan.kumar@email.com",
    clientId: "client_rajan",
    status: "active",
    priority: "high",
    category: "criminal",
    assignedLawyer: "Priya Mehta",
    court: "Sessions Court, Mumbai",
    filingDate: "2024-05-15T00:00:00Z",
    nextHearing: "2024-06-20T10:30:00Z",
    relatedDrafts: ["d1"],
    description:
      "Client charged under IPC Section 420 for alleged fraud. Bail application filed and pending.",
    timeline: [
      {
        id: "tl1",
        date: "2024-05-15T00:00:00Z",
        title: "FIR Filed",
        description: "FIR registered at Andheri Police Station",
        type: "filing",
      },
      {
        id: "tl2",
        date: "2024-05-18T00:00:00Z",
        title: "Arrest & Remand",
        description: "Client arrested, 7-day police remand granted",
        type: "hearing",
      },
      {
        id: "tl3",
        date: "2024-05-28T00:00:00Z",
        title: "Bail Application Filed",
        description: "Bail application filed before Sessions Court",
        type: "draft",
      },
      {
        id: "tl4",
        date: "2024-06-05T00:00:00Z",
        title: "Bail Hearing",
        description: "Arguments heard, case adjourned for further hearing",
        type: "hearing",
      },
    ],
  },
  {
    id: "c2",
    caseNumber: "CAS-2024-0987",
    title: "Property Dispute with Builder Corp",
    clientName: "Sharma Family",
    clientEmail: "sharma.family@email.com",
    clientId: "client_sharma",
    status: "active",
    priority: "medium",
    category: "property",
    assignedLawyer: "Rajesh Sharma",
    court: "Civil Court, Pune",
    filingDate: "2024-04-10T00:00:00Z",
    nextHearing: "2024-06-25T11:00:00Z",
    relatedDrafts: ["d2"],
    description:
      "Property dispute with Builder Corp regarding possession of flat and recovery of advance payment.",
    timeline: [
      {
        id: "tl5",
        date: "2024-04-10T00:00:00Z",
        title: "Suit Filed",
        description: "Civil suit filed for possession and damages",
        type: "filing",
      },
      {
        id: "tl6",
        date: "2024-04-20T00:00:00Z",
        title: "Notice Issued",
        description: "Court issued notice to Builder Corp",
        type: "order",
      },
    ],
  },
  {
    id: "c3",
    caseNumber: "CAS-2024-1103",
    title: "Contested Divorce Petition",
    clientName: "Meena Verma",
    clientEmail: "meena.verma@email.com",
    clientId: "client_meena",
    status: "pending",
    priority: "medium",
    category: "family",
    assignedLawyer: "Arjun Kapoor",
    court: "Family Court, Delhi",
    filingDate: "2024-06-01T00:00:00Z",
    nextHearing: "2024-06-30T10:00:00Z",
    relatedDrafts: ["d3"],
    description:
      "Contested divorce petition. Client seeks divorce on grounds of cruelty and mental harassment.",
    timeline: [
      {
        id: "tl7",
        date: "2024-06-01T00:00:00Z",
        title: "Petition Filed",
        description: "Divorce petition filed under HMA Section 13",
        type: "filing",
      },
    ],
  },
];

export const mockClauses: Clause[] = [
  {
    id: "cl1",
    title: "Arbitration Clause",
    content:
      "Any dispute arising out of or in connection with this Agreement, including any question regarding its existence, validity or termination, shall be referred to and finally resolved by arbitration under the Arbitration and Conciliation Act, 1996.",
    category: "Dispute Resolution",
    tags: ["arbitration", "dispute", "ADR"],
    usageCount: 423,
  },
  {
    id: "cl2",
    title: "Force Majeure",
    content:
      'Neither party shall be liable to the other for any failure to perform any obligation under this Agreement due to an event beyond the reasonable control of such party, including but not limited to acts of God, war, riot, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation, fuel, energy, labor, or materials (hereinafter referred to as "Force Majeure Event").',
    category: "General",
    tags: ["force majeure", "liability", "events"],
    usageCount: 312,
  },
  {
    id: "cl3",
    title: "Confidentiality Clause",
    content:
      "Each party agrees to keep confidential all information received from the other party that is marked as confidential or that reasonably should be understood to be confidential given the nature of the information and circumstances of disclosure.",
    category: "Confidentiality",
    tags: ["NDA", "confidentiality", "trade secret"],
    usageCount: 567,
  },
  {
    id: "cl4",
    title: "Indemnification Clause",
    content:
      "Each party (the Indemnifying Party) shall indemnify, defend, and hold harmless the other party (the Indemnified Party) and its officers, directors, employees, agents, and successors from and against any claims, liabilities, damages, losses, costs, or expenses arising from the Indemnifying Party's breach of this Agreement.",
    category: "Liability",
    tags: ["indemnity", "liability", "damages"],
    usageCount: 289,
  },
  {
    id: "cl5",
    title: "Governing Law",
    content:
      "This Agreement shall be governed by and construed in accordance with the laws of India. The courts of [City] shall have exclusive jurisdiction to settle any dispute which may arise out of or in connection with this Agreement.",
    category: "Jurisdiction",
    tags: ["governing law", "jurisdiction", "Indian law"],
    usageCount: 634,
  },
  {
    id: "cl6",
    title: "Termination Clause",
    content:
      "Either party may terminate this Agreement immediately by written notice if the other party: (a) commits a material breach of any term of this Agreement and fails to cure such breach within thirty (30) days after receiving written notice of the breach; or (b) becomes insolvent, makes a general assignment for the benefit of creditors.",
    category: "Termination",
    tags: ["termination", "breach", "notice"],
    usageCount: 401,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "al1",
    userId: "u2",
    userName: "Priya Mehta",
    action: "CREATED",
    resource: "Draft",
    resourceId: "d1",
    timestamp: "2024-06-07T14:30:00Z",
    ipAddress: "192.168.1.105",
    details: "Created draft: Bail Application — State vs. Rajan Kumar",
  },
  {
    id: "al2",
    userId: "u1",
    userName: "Rajesh Sharma",
    action: "EXPORTED",
    resource: "Draft",
    resourceId: "d5",
    timestamp: "2024-06-07T13:00:00Z",
    ipAddress: "192.168.1.101",
    details: "Exported draft to PDF: Consumer Complaint — Anil Gupta",
  },
  {
    id: "al3",
    userId: "u3",
    userName: "Arjun Kapoor",
    action: "UPDATED",
    resource: "Draft",
    resourceId: "d3",
    timestamp: "2024-06-07T10:00:00Z",
    ipAddress: "192.168.1.108",
    details: "Updated draft version to v2",
  },
  {
    id: "al4",
    userId: "u1",
    userName: "Rajesh Sharma",
    action: "INVITED",
    resource: "User",
    resourceId: "u5",
    timestamp: "2024-06-06T11:00:00Z",
    ipAddress: "192.168.1.101",
    details: "Invited user: Vikram Nair (legal-assistant)",
  },
  {
    id: "al5",
    userId: "u2",
    userName: "Priya Mehta",
    action: "ARCHIVED",
    resource: "Draft",
    resourceId: "d7",
    timestamp: "2024-06-05T09:00:00Z",
    ipAddress: "192.168.1.105",
    details: "Archived draft: FIR Quashing Petition — High Court",
  },
  {
    id: "al6",
    userId: "u1",
    userName: "Rajesh Sharma",
    action: "ROLE_CHANGED",
    resource: "User",
    resourceId: "u4",
    timestamp: "2024-06-04T15:00:00Z",
    ipAddress: "192.168.1.101",
    details: "Changed role: Sneha Patel from lawyer to legal-assistant",
  },
  {
    id: "al7",
    userId: "u5",
    userName: "Vikram Nair",
    action: "CREATED",
    resource: "Draft",
    resourceId: "d8",
    timestamp: "2024-06-08T07:30:00Z",
    ipAddress: "192.168.1.112",
    details: "Created draft: Child Custody Agreement",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    title: "Draft Finalized",
    message:
      "Bail Application for Rajan Kumar has been finalized and is ready to export.",
    type: "success",
    isRead: false,
    timestamp: "2024-06-07T14:30:00Z",
    link: "/drafts/d1",
  },
  {
    id: "n2",
    title: "Export Completed",
    message:
      "Consumer Complaint — Anil Gupta has been exported to PDF successfully.",
    type: "success",
    isRead: false,
    timestamp: "2024-06-07T13:00:00Z",
    link: "/drafts/d5",
  },
  {
    id: "n3",
    title: "Version Restored",
    message:
      "Property Dispute draft has been restored to version 1 by Arjun Kapoor.",
    type: "info",
    isRead: true,
    timestamp: "2024-06-06T16:00:00Z",
    link: "/drafts/d2",
  },
  {
    id: "n4",
    title: "Template Shared",
    message:
      "Priya Mehta shared the Bail Application template with your account.",
    type: "info",
    isRead: true,
    timestamp: "2024-06-06T10:00:00Z",
    link: "/templates",
  },
  {
    id: "n5",
    title: "Hearing Reminder",
    message: "Rajan Kumar case hearing is scheduled for June 20, 2024.",
    type: "warning",
    isRead: false,
    timestamp: "2024-06-08T08:00:00Z",
    link: "/cases/c1",
  },
];

export const mockAnalytics: AnalyticsData[] = Array.from(
  { length: 30 },
  (_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (29 - i));
    return {
      date: date.toISOString().split("T")[0],
      drafts: Math.floor(Math.random() * 8) + 1,
      exports: Math.floor(Math.random() * 5) + 1,
      templates: Math.floor(Math.random() * 4) + 1,
    };
  }
);

export const mockDraftTrends: DraftTrend[] = [
  { month: "Jan", criminal: 12, civil: 18, property: 8, family: 6 },
  { month: "Feb", criminal: 15, civil: 14, property: 11, family: 9 },
  { month: "Mar", criminal: 10, civil: 21, property: 13, family: 7 },
  { month: "Apr", criminal: 18, civil: 16, property: 9, family: 12 },
  { month: "May", criminal: 22, civil: 19, property: 15, family: 10 },
  { month: "Jun", criminal: 8, civil: 12, property: 7, family: 5 },
];

export const dashboardStats = {
  totalDrafts: 142,
  inProgress: 23,
  finalized: 89,
  monthlyExports: 67,
  totalCases: 38,
  activeCases: 22,
  totalUsers: 12,
  templateUsage: 1847,
};

export const recentActivity = [
  {
    id: "ra1",
    user: "Priya Mehta",
    action: "finalized",
    resource: "Bail Application — Rajan Kumar",
    time: "2 hours ago",
    type: "finalized",
  },
  {
    id: "ra2",
    user: "Arjun Kapoor",
    action: "updated",
    resource: "Divorce Petition — Meena vs. Suresh",
    time: "4 hours ago",
    type: "updated",
  },
  {
    id: "ra3",
    user: "Vikram Nair",
    action: "created",
    resource: "Child Custody Agreement",
    time: "5 hours ago",
    type: "created",
  },
  {
    id: "ra4",
    user: "Rajesh Sharma",
    action: "exported",
    resource: "Consumer Complaint — Anil Gupta",
    time: "Yesterday",
    type: "exported",
  },
  {
    id: "ra5",
    user: "Priya Mehta",
    action: "archived",
    resource: "FIR Quashing Petition",
    time: "Yesterday",
    type: "archived",
  },
];
